---
title: "Mirror Mirror on the Wall, Who's the Best Maryland of Them All?"
author: "Sashwat Venkatesh"
date: "2023-10-24"
categories: [news]
format:
  html:
    code-fold: true
---

When Maryland signed Michael Locksley to be their head coach in December of 2018, the fanbase was desperate for improvements across the board. The Terrapins had amassed just 38 wins over the previous 6 years, with just 5 in 2018. Has the former Alabama Offensive Coordinator truly jumped Maryland into greener pastures?

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(lubridate))
suppressMessages(library(ggplot2))
suppressMessages(library(ggrepel))
suppressMessages(data <- read_csv("https://thescoop.org/sports-data-files/footballlogs1123.csv"))
maryland <- data |> filter(TeamFull == "Maryland Terrapins")
maryland <- maryland |> 
  mutate(totalYds = maryland$PassingYds + maryland$RushingYds, 
         defTotalYds = maryland$DefPassingYds + maryland$DefRushingYds
         )

maryland$Result[grepl("W", maryland$Result)] <- 1
maryland$Result[grepl("L", maryland$Result)] <- 0
maryland$Result <- as.integer(maryland$Result)

marylandByYear <- maryland |> 
  group_by(year(Date)) |> 
  summarise(avgOffYds = sum(totalYds)/sum(OffensivePlays), avgDefYds = sum(defTotalYds)/sum(DefPlays), wins = sum(Result))

avgs <- marylandByYear |> 
  ungroup() |> 
  summarise(
    offense = mean(avgOffYds), 
    defense = mean(avgDefYds)
    )

ggplot() + 
  geom_point(
    data=marylandByYear, aes(x=avgOffYds, y=avgDefYds, size=wins, color="red")
    ) +
  geom_vline(xintercept = avgs$offense) +
  geom_hline(yintercept = avgs$defense) +
  geom_text_repel(data=marylandByYear, aes(x=avgOffYds, y=avgDefYds, label=`year(Date)`)) +
  labs(title="A Shift To Offense Since Locksley's Inception", subtitle="4 of Locksley's 5 seasons leading the Terps have seen above average offensive production" , caption="Source: NCAA Data 2011-2023 | By Sashwat Venkatesh")  + theme_minimal()


```

From the data, we can clearly show that Michael Locksley has kickstarted a new era of Terrapins Football. Since he took over as head coach in 2019, in every season since and including 2020, Maryland's average offensive yards per play has been above program average since 2011, 3 of those 4 years have seen lower than program average yards allowed per play while on defense.

Locksley's tenure has also seen 25 wins thus far, with a rocky start in 2019 and 2020, earning just 5 wins across the two years. However, since 21, the program has won 20 games, including 2 bowl victories. So, safe to say, while there was a bumpy start, Maryland has "Locked In".
